<?php

/**
 * @file
 * Install, update and uninstall functions for the Smart Menu module.
 */

/**
* Implements hook_uninstall().
*/
function smart_menu_uninstall() {
  // Clean-up layout configuration files.
  $config = config_get('smart_menu.settings');
  foreach ($config as $layout_name => $uuid) {
    config_clear('layout.layout.' . $layout_name,'content.' . $uuid . '.data.settings.block_settings.advanced');
  }
  // Finally delete own configuration file.
  config('smart_menu.settings')->delete();
  // Flash cache.
  backdrop_flush_all_caches();
}
